"use client";

import { Button } from "@/components/ui/button";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export default function DownloadReport() {
  const handleDownload = async () => {
    try {
      const chart = document.querySelector("canvas");
      const aiBox = document.querySelector("#ai-response");

      if (!chart) {
        alert("⚠️ No chart found to include in the report!");
        return;
      }

      // ✅ Optional: read dataset name from localStorage (if saved)
      const storedData = localStorage.getItem("csvData");
      const datasetName = localStorage.getItem("csvFileName") || "Uploaded CSV";

      // 🧱 Create sandbox to isolate Tailwind oklch colors
      const clone = chart.cloneNode(true) as HTMLElement;
      const sandbox = document.createElement("div");
      sandbox.setAttribute("data-html2canvas-ignore", ""); // 👉 triggers RGB fallback in globals.css
      sandbox.style.position = "fixed";
      sandbox.style.top = "-9999px";
      sandbox.style.left = "-9999px";
      sandbox.style.width = "800px";
      sandbox.style.backgroundColor = "#ffffff";
      sandbox.style.color = "#000000";
      sandbox.style.padding = "20px";
      sandbox.style.border = "1px solid #ddd";
      sandbox.appendChild(clone);
      document.body.appendChild(sandbox);

      // 🧩 Try capturing chart — with fallback if html2canvas fails
      let chartCanvas;
      try {
        chartCanvas = await html2canvas(sandbox, {
          backgroundColor: "#ffffff",
          scale: 2,
          useCORS: true,
          logging: false,
          onclone: (docClone) => {
            docClone.querySelectorAll("*").forEach((el) => {
              const e = el as HTMLElement;
              e.style.filter = "none";
              e.style.boxShadow = "none";
              e.style.colorScheme = "light";
              e.style.background = "#ffffff";
              e.style.backgroundImage = "none";
            });
          },
        });
      } catch (err) {
        console.warn("⚠️ html2canvas failed — using direct canvas fallback:", err);
        // fallback: directly copy canvas pixels to a new element
        const realCanvas = chart as HTMLCanvasElement;
        const tempCanvas = document.createElement("canvas");
        tempCanvas.width = realCanvas.width;
        tempCanvas.height = realCanvas.height;
        const ctx = tempCanvas.getContext("2d");
        ctx?.drawImage(realCanvas, 0, 0);
        chartCanvas = tempCanvas;
      }

      // 🧹 Clean up sandbox
      document.body.removeChild(sandbox);

      // 🧾 Generate PDF
      const pdf = new jsPDF("p", "mm", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();

      // Convert captured chart to image
      const chartData = chartCanvas.toDataURL("image/png");
      const chartWidth = pageWidth - 30;
      const chartHeight = (chartCanvas.height * chartWidth) / chartCanvas.width;

      // 🏷️ PDF Header
      pdf.setFontSize(18);
      const logo = "/logo.png";
      pdf.addImage(logo, "PNG", 150, 5, 40, 15);
      pdf.text("📊 InsightBoard.AI Report", 15, 15);
      pdf.setFontSize(12);
      pdf.text(`Dataset: ${datasetName}`, 15, 22);
      pdf.addImage(chartData, "PNG", 15, 30, chartWidth, chartHeight);

      // 💬 AI Insight Section
      const aiText = aiBox?.textContent?.trim() || "No AI analysis available.";
      const yPos = chartHeight + 50;
      pdf.setFontSize(14);
      pdf.text("💬 AI Insight Summary:", 15, yPos);
      pdf.setFontSize(12);
      const splitText = pdf.splitTextToSize(aiText, pageWidth - 30);
      pdf.text(splitText, 15, yPos + 10);

      // 🕒 Footer
      pdf.setFontSize(10);
      pdf.text(
        `Generated by InsightBoard.AI • ${new Date().toLocaleString()}`,
        15,
        290
      );

      // 💾 Save file
      pdf.save("InsightReport.pdf");
    } catch (err) {
      console.error("❌ PDF generation failed:", err);
      alert("❌ Failed to generate report. Please try again.");
    }
  };

  return (
    <div className="flex justify-center mt-4">
      <Button
        onClick={handleDownload}
        className="bg-indigo-600 hover:bg-indigo-700 text-white"
      >
        📄 Download AI Report
      </Button>
    </div>
  );
}
